configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internet-facing
    ingressClassName: "alb"
  ingressGrpc:
    enabled: true
    isAWSALB: true
    ingressClassName: "alb"
